### ISSUE TITLE
在python解释器中无法执行这样的命令吗？ “python test.py”

### ISSUE THREAD

**Issue by xylcbd** [Vamei/Python-Tutorial-Vamei#2]
Create intermediate03.md 中好像没有说明*.py是怎么执行的，我试了下，在解释器中好像没法执行这样的命令 “python test.py”，一定要切换到普通cmd窗口下。
这是就这样设计的，还是有其他方法呢 ？

另，希望能将*.py的load执行方法再加上去 ~

**Comment by Vamei** [comment]
在解释器内部无法使用python test.py。python是一个应用，而不是Python的关键字。
在最开始，有提到.py文件的执行方法。应该是第一章吧。

**Comment by xylcbd** [comment]
是这样啊，清楚了，感谢回复。
